
import AuthContext from '@/components/authcontext'
import { SessionProvider } from 'next-auth/react'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getSession() {
  const res = await fetch("http://localhost:3000/api/session")
  const session = await res.json()
  console.log("getting sessions")
  console.log(`session - ${session}`)
  return session
}

export default async function RootLayout({
  children 
}) {
  const session = await getSession();

  return (
    <html lang="en">
        <body>
          <AuthContext session={session}>
            {children}
          </AuthContext>
        </body>
      
    </html>
  )
}

