
import AuthContext from '@/components/authcontext'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { getServerSession, Session } from 'next-auth'
import { SessionProvider } from 'next-auth/react'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children 
}: {children: React.ReactNode}) {
  return (
    <html lang="en">
        <body>
          <AuthContext >
            {children}
          </AuthContext>
        </body>
      
    </html>
  )
}

